-- Create Categories Table
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Products Table
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  price numeric not null,
  stock integer not null default 0,
  category_id bigint references public.categories(id),
  image_url text, -- Main image
  images text[], -- Additional images
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.categories enable row level security;
alter table public.products enable row level security;

-- Create Policies (Public Read, Authenticated Write)
create policy "Public categories are viewable by everyone."
  on public.categories for select
  using ( true );

create policy "Public products are viewable by everyone."
  on public.products for select
  using ( true );

create policy "Authenticated users can insert categories."
  on public.categories for insert
  with check ( auth.role() = 'authenticated' );

create policy "Authenticated users can update categories."
  on public.categories for update
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can delete categories."
  on public.categories for delete
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can insert products."
  on public.products for insert
  with check ( auth.role() = 'authenticated' );

create policy "Authenticated users can update products."
  on public.products for update
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can delete products."
  on public.products for delete
  using ( auth.role() = 'authenticated' );

-- Storage Buckets
-- You need to create a bucket named 'products' and 'categories' in your Supabase dashboard.
-- Policy for 'products' bucket:
-- Give public read access to everyone.
-- Give insert/update/delete access to authenticated users.
