  stock integer not null default 0,
  category_id bigint references public.categories(id),
  image_url text, -- Main image
  images text[], -- Additional images
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.categories enable row level security;
alter table public.products enable row level security;

-- Create Policies (Public Read, Authenticated Write)
create policy "Public categories are viewable by everyone."
  on public.categories for select
  using ( true );

create policy "Public products are viewable by everyone."
  on public.products for select
  using ( true );

create policy "Authenticated users can insert categories."
  on public.categories for insert
  with check ( auth.role() = 'authenticated' );

create policy "Authenticated users can update categories."
  on public.categories for update
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can delete categories."
  on public.categories for delete
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can insert products."
  on public.products for insert
  with check ( auth.role() = 'authenticated' );

create policy "Authenticated users can update products."
  on public.products for update
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can delete products."
  on public.products for delete
  using ( auth.role() = 'authenticated' );

-- Storage Buckets
-- You need to create a bucket named 'products' and 'categories' in your Supabase dashboard.
-- Policy for 'products' bucket:
-- Give public read access to everyone.
-- Give insert/update/delete access to authenticated users.
-- Create Profiles Table
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  full_name text,
  phone text,
  address text,
  role text default 'customer' check (role in ('customer', 'admin')),
  status text default 'active' check (status in ('active', 'inactive')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on Profiles
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

create policy "Admins can update any profile."
  on public.profiles for update
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );

-- Trigger to create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role, status)
  values (new.id, new.raw_user_meta_data->>'full_name', 'customer', 'active');
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create Addresses Table
create table public.addresses (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null,
  full_name text,
  address_line1 text not null,
  address_line2 text,
  city text not null,
  state text not null,
  postal_code text not null,
  country text not null,
  is_default boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on Addresses
alter table public.addresses enable row level security;

create policy "Users can view their own addresses."
  on public.addresses for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own addresses."
  on public.addresses for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own addresses."
  on public.addresses for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own addresses."
  on public.addresses for delete
  using ( auth.uid() = user_id );




  -- Add product_type to products
alter table public.products add column if not exists product_type text default 'simple' check (product_type in ('simple', 'variant'));

-- Create Attributes Table
create table public.attributes (
  id bigint generated by default as identity primary key,
  name text not null unique,
  type text not null check (type in ('text', 'number', 'select')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Product Variants Table
create table public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade not null,
  sku text,
  price numeric not null,
  stock integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Product Variant Attributes Table
create table public.product_variant_attributes (
  id bigint generated by default as identity primary key,
  variant_id bigint references public.product_variants(id) on delete cascade not null,
  attribute_id bigint references public.attributes(id) on delete cascade not null,
  value text not null,
  unique(variant_id, attribute_id)
);

-- Enable RLS
alter table public.attributes enable row level security;
alter table public.product_variants enable row level security;
alter table public.product_variant_attributes enable row level security;

-- Policies for Attributes (Admin manage, Public read)
create policy "Public attributes are viewable by everyone." on public.attributes for select using (true);
create policy "Admins can insert attributes." on public.attributes for insert with check (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can update attributes." on public.attributes for update using (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can delete attributes." on public.attributes for delete using (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));

-- Policies for Product Variants (Public read, Admin manage)
create policy "Public variants are viewable by everyone." on public.product_variants for select using (true);
create policy "Admins can insert variants." on public.product_variants for insert with check (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can update variants." on public.product_variants for update using (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can delete variants." on public.product_variants for delete using (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));

-- Policies for Variant Attributes (Public read, Admin manage)
create policy "Public variant attributes are viewable by everyone." on public.product_variant_attributes for select using (true);
create policy "Admins can insert variant attributes." on public.product_variant_attributes for insert with check (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can update variant attributes." on public.product_variant_attributes for update using (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can delete variant attributes." on public.product_variant_attributes for delete using (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));


alter table public.product_variants
add column if not exists image_url text,
add column if not exists images text[];

-- Create Cart Items Table
create table public.cart_items (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null,
  product_id bigint references public.products(id) on delete cascade not null,
  variant_id bigint references public.product_variants(id) on delete cascade,
  quantity integer not null default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, product_id, variant_id)
);

-- Enable RLS on Cart Items
alter table public.cart_items enable row level security;

create policy "Users can view their own cart items."
  on public.cart_items for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own cart items."
  on public.cart_items for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own cart items."
  on public.cart_items for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own cart items."
  on public.cart_items for delete
  using ( auth.uid() = user_id );

alter table product_variants add column is_default boolean default false;
