
-- Create Reviews Table
create table public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  product_id bigint references public.products(id) on delete cascade not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, product_id) -- One review per product per user
);

-- Enable RLS on Reviews
alter table public.reviews enable row level security;

-- Policies for Reviews
create policy "Public reviews are viewable by everyone."
  on public.reviews for select
  using ( true );

create policy "Authenticated users can insert reviews."
  on public.reviews for insert
  with check ( auth.role() = 'authenticated' AND auth.uid() = user_id );

create policy "Users can update their own reviews."
  on public.reviews for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own reviews."
  on public.reviews for delete
  using ( auth.uid() = user_id );
